# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"
require 'fhir_client'

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/test_*.rb"]
end

task default: :test

spec = Gem::Specification.find_by_name 'fhir_client'
load "#{spec.gem_dir}/lib/fhir_client/tasks/tasks.rake"
